import 'dart:typed_data';

import 'credito_pdf_assets.dart';
import 'credito_pdf_shared.dart';
import 'generate_autorizacion_descuentos_pdf.dart';
import 'generate_pagare_pdf.dart';

/// Pagaré (2 secciones) + autorización nómina en un solo PDF para ZapSign.
Future<Uint8List> buildCreditoDocumentosFirmaPdf({
  required String tipoLineaCredito,
  required String numeroPagare,
  required String fechaApertura,
  required String nombresPrincipal,
  required String tipoDocumentoPrincipal,
  required String numeroDocumentoPrincipal,
  required String fechaExpedicionPrincipal,
  required String ciudadExpedicionPrincipal,
  required String direccionResidenciaPrincipal,
  required String ciudadResidenciaPrincipal,
  required String barrioPrincipal,
  required String correoElectronicoPrincipal,
  required String whatsappPrincipal,
  required String otroTelefonoPrincipal,
  required String nombresCodeudor,
  required String tipoDocumentoCodeudor,
  required String numeroDocumentoCodeudor,
  required String fechaExpedicionCodeudor,
  required String ciudadExpedicionCodeudor,
  required String direccionResidenciaCodeudor,
  required String ciudadResidenciaCodeudor,
  required String barrioCodeudor,
  required String correoElectronicoCodeudor,
  required String whatsappCodeudor,
  required String otroTelefonoCodeudor,
  required String valorCapitalLetras,
  required String valorCapitalNumeros,
  required String valorInteresesLetras,
  required String valorInteresesNumeros,
  required String diaPagare,
  required String mesPagare,
  required String anioPagare,
  required String ciudadSuscripcion,
  required String departamentoSuscripcion,
  required String ciudadCumplimiento,
  required String diaCumplimiento,
  required String mesCumplimiento,
  required String anioCumplimiento,
  required String nombres,
  required String tipoDocumento,
  required String numeroDocumento,
  required String fechaExpedicion,
  required String ciudadExpedicion,
  required String correoElectronico,
  required String whatsapp,
  required String otroTelefono,
}) async {
  await creditoPdfEnsureFonts();
  final pdf = creditoPdfNewDocument();
  final assets = await creditoPdfLoadAssets();

  creditoPdfAddPagarePages(
    pdf,
    assets: assets,
    tipoLineaCredito: tipoLineaCredito,
    numeroPagare: numeroPagare,
    fechaApertura: fechaApertura,
    nombresPrincipal: nombresPrincipal,
    tipoDocumentoPrincipal: tipoDocumentoPrincipal,
    numeroDocumentoPrincipal: numeroDocumentoPrincipal,
    fechaExpedicionPrincipal: fechaExpedicionPrincipal,
    ciudadExpedicionPrincipal: ciudadExpedicionPrincipal,
    direccionResidenciaPrincipal: direccionResidenciaPrincipal,
    ciudadResidenciaPrincipal: ciudadResidenciaPrincipal,
    barrioPrincipal: barrioPrincipal,
    correoElectronicoPrincipal: correoElectronicoPrincipal,
    whatsappPrincipal: whatsappPrincipal,
    otroTelefonoPrincipal: otroTelefonoPrincipal,
    nombresCodeudor: nombresCodeudor,
    tipoDocumentoCodeudor: tipoDocumentoCodeudor,
    numeroDocumentoCodeudor: numeroDocumentoCodeudor,
    fechaExpedicionCodeudor: fechaExpedicionCodeudor,
    ciudadExpedicionCodeudor: ciudadExpedicionCodeudor,
    direccionResidenciaCodeudor: direccionResidenciaCodeudor,
    ciudadResidenciaCodeudor: ciudadResidenciaCodeudor,
    barrioCodeudor: barrioCodeudor,
    correoElectronicoCodeudor: correoElectronicoCodeudor,
    whatsappCodeudor: whatsappCodeudor,
    otroTelefonoCodeudor: otroTelefonoCodeudor,
    valorCapitalLetras: valorCapitalLetras,
    valorCapitalNumeros: valorCapitalNumeros,
    valorInteresesLetras: valorInteresesLetras,
    valorInteresesNumeros: valorInteresesNumeros,
    diaPagare: diaPagare,
    mesPagare: mesPagare,
    anioPagare: anioPagare,
    ciudadSuscripcion: ciudadSuscripcion,
    departamentoSuscripcion: departamentoSuscripcion,
    ciudadCumplimiento: ciudadCumplimiento,
    diaCumplimiento: diaCumplimiento,
    mesCumplimiento: mesCumplimiento,
    anioCumplimiento: anioCumplimiento,
  );

  creditoPdfAddAutorizacionPage(
    pdf,
    assets: assets,
    nombres: nombres,
    tipoDocumento: tipoDocumento,
    numeroDocumento: numeroDocumento,
    fechaExpedicion: fechaExpedicion,
    ciudadExpedicion: ciudadExpedicion,
    correoElectronico: correoElectronico,
    whatsapp: whatsapp,
    otroTelefono: otroTelefono,
    tipoLineaCredito: tipoLineaCredito,
  );

  return creditoPdfSave(pdf);
}
